name = "SortingLab"
uuid = "562c1548-17b8-5b69-83cf-d8aebec229f5"
authors = ["Dai ZJ <zhuojia.dai@gmail.com>"]
version = "0.2.5"

[deps]
CategoricalArrays = "324d7699-5711-5eae-9e2f-1d82baa6b597"
SortingAlgorithms = "a2af1166-a08f-5f64-846c-94a0d3cef48c"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"

[compat]
CategoricalArrays = "0.7, 0.8, 0.9"
SortingAlgorithms = "0.3"
StatsBase = "0.32, 0.33"
julia = "1"

[extras]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
FastGroupBy = "e6aeac8e-85c6-520e-8612-effc59bc0f33"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Random", "DataFrames", "FastGroupBy", "Statistics"]
